### ISSUE TITLE
Titlebar Component

### ISSUE THREAD

**Issue by Meschreiber** [stefsulzer/weTravel#18]
- (Editable) title for trip
- Who is logged in
- Ability to log out

**Comment by TinaHeiligers** [comment]
We currently handle a case for new signup.
 +    // We need to consider the case for when someone is logged in aand has info in the database. In this case, we want to get their
 +    // details from the database if they exist and if they don't exist, give the prompts.
 +    // some ternary like: if there is a logged in user and they have a name in the db, return the name. Otherwise return 'plase enter a name'.
 +    // same double condition needed for homeBase: if user logged in AND user has a
